clone:
  git:
    image: plugins/git
  when:
    branch: master

pipeline:
  hubpublish:
    image: plugins/docker
    repo: servercentral/praeco
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deployment:
    image: registry.servercentral.com/drone-plugins/awxdeployment
    pull: true
    environment:
      - PROJECT_PLAYBOOK=playbooks/public-docker-cluster/praeco.yml
    volumes:
      - /etc/tower/tower_cli.cfg:/etc/tower/tower_cli.cfg
    when:
      event: push
      branch: master 
      status: success
